name: Test Suite

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"


jobs:

  tests:
    uses: ./.github/workflows/tests.yml
