name: CI/CD

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:

  tests:
    uses: ./.github/workflows/jobs/tests.yml

  build_and_push_to_docker_hub:
    needs: tests
    uses: ./.github/workflows/jobs/build_push.yml
    secrets: inherit

  server_environment:
    needs: tests
    uses: ./.github/workflows/jobs/server_environ.yml
    secrets: inherit

  deploy:
    needs: [build_and_push_to_docker_hub, server_environment]
    uses: ./.github/workflows/jobs/deploy.yml
    secrets: inherit
