name: CI/CD

on: ["push"]
#  push:
#    branches: ["develop"]
#  workflow_dispatch:

jobs:

  tests:
    uses: ./.github/workflows/tests.yml

  build_and_push_to_docker_hub:
    needs: tests
    uses: ./.github/workflows/build_push.yml
    with:
      back_or_front: backend
    secrets: inherit
